name: Run Test Python
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -U pytest
    
    - name: Run Test Ejercicio 1
      run: |
        pytest "Tarea 1.1 - Archivo/test.py" -v -s
        
    - name: Run Test Ejercicio 2
      run: |
        pytest "Tarea 1.2 - Ascensor/Intento 1 (No cumple los requerimientos)/Test.py" -v -s
        
    - name: Run Test Ejercicio 2.1
      run: |
        pytest "Tarea 1.2 - Ascensor/Intento 2/Test.py" -v -s
    
    - name: Run Test Ejercicio 3
      run: |
        pytest "Tarea 1.3 - Piedra Papel Tijera/Test.py" -v -s
        
    - name: Run Test Ejercicio 4
      run: |
        pytest "Tarea BlockChain/test.py" -v -s

    - name: Run Test Tp 1
      run: |
        pytest "Tp 1/PatronProxy/test.py" -v -s
